---
- name: Download the k9s archive.
  get_url:
    url: "{{ k9s_download_url }}"
    dest: /tmp
    checksum: sha256:{{ k9s_checksum_url }}
    mode: 0755
  register: k9s_download

- name: Unarchive the k9s archive.
  unarchive:
    src: "{{ k9s_download.dest }}"
    dest: /tmp
    mode: 0755
    remote_src: true

- name: Copy the k9s binary into place.
  copy:
    src: /tmp/k9s
    dest: "{{ k9s_bin_path }}"
    mode: 0755
    remote_src: true
  become: true
