---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_IMAGE:-ubuntu2204}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-/usr/sbin/init}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:${MOLECULE_DOCKER_VOLUMES:-rw}
    cgroupns_mode: ${MOLECULE_DOCKER_CGROUPS_MODE:-host}
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
