---
name: Release

'on':
  release:
    types: [published]

defaults:
  run:
    working-directory: 'm18unet.k9s'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v4
        with:
          path: 'm18unet.k9s'

      - name: Setup Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: |-
          GITHUB_USER=$(echo ${{ github.repository }} | cut -d/ -f1)
          GITHUB_REPO=$(echo ${{ github.repository }} | cut -d/ -f2)
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} ${GITHUB_USER} ${GITHUB_REPO}
